version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jobmarket.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  streamlit-dashboard:
    build: ./streamlit_dashboard
    ports:
      - "8501:8501"
    volumes:
      - "./streamlit_dashboard:/usr/src/app"

  api_backend:
    build: ./api_backend
    ports:
      - 8000:8000
    volumes:
      - "./api_backend:/usr/src/app"
    restart: always
    environment:
      - WATCHFILES_FORCE_POLLING=true
    container_name: api_backend

volumes:
  postgres-data:
  pgadmin-data: